# These are supported funding model platforms
# These are supported funding model platforms

github: [DarkSpaceSoftwareAndSecurity]
patreon: darkspacesoftware
open_collective: darkspacesoftware
ko_fi: darkspace
tidelift: npm/wordpress-node
community_bridge: wordpress-node
liberapay: darkspace
issuehunt: wordpress-node
lfx_crowdfunding: wordpress-node
polar: darkspace
buy_me_a_coffee: darkspace
thanks_dev: darkspace
custom:
  - https://darkspacesoftwareandsecurity.com/donate
  - https://wordpress-node.org/support
