@echo off
REM ═══════════════════════════════════════════════════════════════════════════════
REM NodePress CMS - Docker-Based Setup (No Admin Required)
REM Uses Docker for PostgreSQL and Redis, runs app locally
REM ═══════════════════════════════════════════════════════════════════════════════

setlocal enabledelayedexpansion
color 0B

echo.
echo ===============================================================
echo       NodePress CMS - Docker-Based Setup
echo       (Prerequisites: Node.js 18+, Docker Desktop)
echo ===============================================================
echo.

REM Get the directory where this batch file is located
set SCRIPT_DIR=%~dp0
set APP_DIR=%SCRIPT_DIR%..

cd /d "%APP_DIR%"

REM Check Node.js
where node >nul 2>&1
if %errorLevel% neq 0 (
    color 0C
    echo [ERROR] Node.js not found! Please install Node.js 18+ first.
    echo Download from: https://nodejs.org/
    pause
    exit /b 1
)
echo [OK] Node.js found

REM Check Docker
where docker >nul 2>&1
if %errorLevel% neq 0 (
    color 0C
    echo [ERROR] Docker not found! Please install Docker Desktop first.
    echo Download from: https://www.docker.com/products/docker-desktop/
    pause
    exit /b 1
)
echo [OK] Docker found

REM Check if Docker is running
docker info >nul 2>&1
if %errorLevel% neq 0 (
    color 0C
    echo [ERROR] Docker is not running! Please start Docker Desktop.
    pause
    exit /b 1
)
echo [OK] Docker is running

echo.
echo [STEP 1/7] Starting PostgreSQL and Redis containers...
docker-compose -f docker-compose.dev.yml up -d
if %errorLevel% neq 0 (
    color 0C
    echo [ERROR] Failed to start Docker containers!
    pause
    exit /b 1
)
echo [OK] Containers started

REM Wait for PostgreSQL to be ready
echo [INFO] Waiting for PostgreSQL to be ready...
timeout /t 5 /nobreak >nul

REM Create .env if it doesn't exist
if not exist "%APP_DIR%\.env" (
    echo.
    echo [STEP 2/7] Creating .env file...
    (
        echo # NodePress Development Environment
        echo # Generated by docker-setup.bat
        echo.
        echo # Database - Docker PostgreSQL
        echo DATABASE_URL=postgresql://nodepress:nodepress123@localhost:5432/nodepress
        echo.
        echo # Redis - Docker Redis
        echo REDIS_HOST=localhost
        echo REDIS_PORT=6379
        echo.
        echo # Server
        echo PORT=3000
        echo NODE_ENV=development
        echo.
        echo # Security - Change these in production!
        echo JWT_SECRET=dev-jwt-secret-change-in-production-12345
        echo SESSION_SECRET=dev-session-secret-change-in-production-12345
        echo.
        echo # Admin Account
        echo ADMIN_EMAIL=admin@starter.dev
        echo ADMIN_PASSWORD=Admin@Secure2024!
        echo.
        echo # Site Configuration
        echo SITE_NAME=NodePress
        echo SITE_DESCRIPTION=A modern CMS built with Node.js
        echo ACTIVE_THEME=my-theme
    ) > "%APP_DIR%\.env"
    echo [OK] .env file created
) else (
    echo [STEP 2/7] .env file already exists, skipping...
)

echo.
echo [STEP 3/7] Installing backend dependencies...
call npm install
if %errorLevel% neq 0 (
    color 0E
    echo [WARNING] npm install had issues, trying to continue...
)
echo [OK] Backend dependencies installed

echo.
echo [STEP 4/7] Installing admin panel dependencies...
cd admin
call npm install
cd ..
echo [OK] Admin dependencies installed

echo.
echo [STEP 5/7] Generating Prisma client...
call npx prisma generate
if %errorLevel% neq 0 (
    color 0C
    echo [ERROR] Prisma generate failed!
    pause
    exit /b 1
)
echo [OK] Prisma client generated

echo.
echo [STEP 6/7] Pushing database schema...
call npx prisma db push
if %errorLevel% neq 0 (
    color 0C
    echo [ERROR] Database schema push failed!
    pause
    exit /b 1
)
echo [OK] Database schema applied

echo.
echo [STEP 7/7] Seeding database...
call npx prisma db seed
if %errorLevel% neq 0 (
    color 0E
    echo [WARNING] Database seeding had issues, but continuing...
)
echo [OK] Database seeded

REM Create directories
if not exist "%APP_DIR%\uploads" mkdir "%APP_DIR%\uploads"
if not exist "%APP_DIR%\backups" mkdir "%APP_DIR%\backups"

color 0A
echo.
echo ===============================================================
echo       Setup Complete!
echo ===============================================================
echo.
echo Docker containers running:
echo   - PostgreSQL: localhost:5432
echo   - Redis:      localhost:6379
echo.
echo To start the application:
echo   npm run dev
echo.
echo Access:
echo   Admin Panel: http://localhost:3000/admin
echo   API:         http://localhost:3000/api
echo.
echo Default login:
echo   Email:    admin@starter.dev
echo   Password: Admin@Secure2024!
echo.
echo To stop Docker containers:
echo   docker-compose -f docker-compose.dev.yml down
echo.
pause

